*STEP 7 - REMOVE OBSERVATIONS WITHOUT YEAR OF BIRTH;

LIBNAME PSID "U:\1Projects\PSID\WAVE37\WORKFILES";

DATA PSID.HOUSEHOLDHEADSELECTEDVARSYRBORNW;
SET PSID.HOUSEHOLDHEADSELECTEDVARSWLTH ;
IF HYBRID_INDIVYEAROFBIRTH = . THEN DELETE;
RUN;

/*
NOTE: There were 73251 observations read from the data set PSID.HOUSEHOLDHEADSELECTEDVARSWLTH.
NOTE: The data set PSID.HOUSEHOLDHEADSELECTEDVARSYRBORNW has 73140 observations and 2438
      variables.
*/

