*STEP 6B - CREATE YEAR OF BIRTH VARIABLE;

LIBNAME PSID "U:\1Projects\PSID\WAVE37\WORKFILES";


*Note the frequency table of yearborn2009 indicates that 46,900 did not have year of birth information. This is 65.79 percent of the total (71,285) individuals.
Thus, using the yearofbirth variable is one of the major reasons for the reduction of observations in the final life table datasets;


DATA INDIVYEARBORN
(KEEP =
ER30001
ER30002
YEARBORN1983
YEARBORN1984
YEARBORN1985
YEARBORN1986
YEARBORN1987
YEARBORN1988
YEARBORN1989
YEARBORN1990
YEARBORN1991
YEARBORN1992
YEARBORN1993
YEARBORN1994
YEARBORN1995
YEARBORN1996
YEARBORN1997
YEARBORN1999
YEARBORN2001
YEARBORN2003
YEARBORN2005
YEARBORN2007
YEARBORN2009
YEARBORN2011
);
SET PSID.HOUSEHOLDHEADSELECTEDVARSWLTH; 
RUN;

PROC FREQ DATA = INDIVYEARBORN;
TABLE yearborn1983--yearborn2011;
RUN;

PROC TRANSPOSE DATA = INDIVYEARBORN OUT = YEARBORNINDIV (RENAME = (COL1 = INDIVYEAROFBIRTH));
BY ER30001 ER30002;
RUN;

PROC FREQ DATA = YEARBORNINDIV;
TABLE INDIVYEAROFBIRTH;
*WHERE TRIM(LEFT(_NAME_)) = "YEARBORN2005";
RUN;


DATA INDIVYEAROFBIRTH;
SET  YEARBORNINDIV;
IF INDIVYEAROFBIRTH IN (.,0,9999) THEN DELETE;
RUN;

PROC FREQ DATA = INDIVYEAROFBIRTH;
TABLE INDIVYEAROFBIRTH;
*WHERE TRIM(LEFT(_NAME_)) = "YEARBORN2005";
RUN;


PROC SQL;
CREATE TABLE INDIVYEAROFBIRTH1 AS
SELECT ER30001, ER30002, INDIVYEAROFBIRTH, COUNT(*) AS NUMOBS
FROM INDIVYEAROFBIRTH
GROUP BY ER30001, ER30002, INDIVYEAROFBIRTH
ORDER BY ER30001, ER30002, NUMOBS DESC  ; 
QUIT;

PROC SORT DATA = INDIVYEAROFBIRTH1 OUT = INDIVYEAROFBIRTH2;
BY ER30001 ER30002 DESCENDING NUMOBS;
RUN;

ODS GRAPHICS OFF;
ODS HTML CLOSE;
ODS LISTING;

PROC FREQ DATA = INDIVYEAROFBIRTH2;
TABLE INDIVYEAROFBIRTH;
*WHERE TRIM(LEFT(_NAME_)) = "YEARBORN2005";
RUN;

/*select year of birth.  if individual has more than one year of birth across wave, choose the most frequently entered/used */

DATA PSID.INDIVYEAROFBIRTHWLTH (DROP = NUMOBS);
SET INDIVYEAROFBIRTH2;
BY ER30001 ER30002 DESCENDING NUMOBS;
IF FIRST.ER30001 OR FIRST.ER30002;
RUN;

/*
NOTE: There were 69167 observations read from the data set WORK.INDIVYEAROFBIRTH2.
NOTE: The data set PSID.INDIVYEAROFBIRTHWLTH has 61596 observations and 3 variables.


There were 61,596 OBSERVATIONS WITH YEAR OF BIRTH VALUES.  This is 94.42 percent (11,666 obs) of the total (73,251) individuals.
Thus, using the yearofbirth variable is one of the major reasons for the reduction of observations in the final life table datasets;;

*/
PROC FREQ DATA = PSID.INDIVYEAROFBIRTHWLTH; 
TABLE INDIVYEAROFBIRTH ;
RUN;


DATA PSID.HOUSEHOLDHEADSELECTEDVARSWLTH;
MERGE PSID.HOUSEHOLDHEADSELECTEDVARSWLTH (IN=A) PSID.INDIVYEAROFBIRTHWLTH;
BY ER30001 ER30002;
*IF A = 1;
*LABEL VAR INDIVYEAROFBIRTH = "Frequently cited Year of Birth of the individual across all waves";
RUN;

/*
NOTE: There were 73251 observations read from the data set PSID.HOUSEHOLDHEADSELECTEDVARSWLTH.
NOTE: There were 61596 observations read from the data set PSID.INDIVYEAROFBIRTHWLTH.
NOTE: The data set PSID.HOUSEHOLDHEADSELECTEDVARSWLTH has 73251 observations and 2435
      variables.

*/





/*OPTIONAL -- find individuals with multiple year of birth*/


/*
PROC SQL;
CREATE TABLE PSID.INDIVYEAROFBIRTH2DUPLICATES AS
SELECT A.*, B.DUPNO 
FROM INDIVYEAROFBIRTH2 A, (SELECT ER30001, ER30002, COUNT(*) AS DUPNO FROM INDIVYEAROFBIRTH2 GROUP BY ER30001, ER30002 ) B
WHERE A.ER30001 = B.ER30001 AND A.ER30002 = B.ER30002 AND DUPNO > 1
ORDER BY ER30001, ER30002;
QUIT;
*/
